### ISSUE TITLE
[front] Tailwind button

### ISSUE THREAD

**Issue by kevinmamaqi** [it-academyproject/ita-directory#218]
Refactor units/button to include tailwind styles

**Comment by ManuC84** [comment]
1. Muchos botones tienen en el texto un margin left directamente añadido en el jsx desde antes. Si se quita el texto quedaría centrado.  
2. Está bien esta forma de trabajar? Sigo con todos igual?

![tw-macros](https://user-images.githubusercontent.com/66978893/133427045-fb4dcb90-4277-47d5-ba60-901aa754caa8.png)

![example-button2](https://user-images.githubusercontent.com/66978893/133427040-2dc87af8-c35d-449f-a9e3-e79538c0d9e3.PNG)
![example-button1](https://user-images.githubusercontent.com/66978893/133427043-1c93ada7-4e4f-4522-9b4f-704d13143e0f.PNG)

**Comment by kevinmamaqi** [comment]
Tiene buena pinta pero no entiendo bien lo del margen a la izquierda. Si el botón se invoca en un sitio dado y se le quiere pasar un margen especifico esta bien. El problema es tenerlo hardcodeado.


PS: Excelente issue. Muy bien hecho.

**Comment by ManuC84** [comment]
> Tiene buena pinta pero no entiendo bien lo del margen a la izquierda. Si el botón se invoca en un sitio dado y se le quiere pasar un margen especifico esta bien. El problema es tenerlo hardcodeado.
> 
> PS: Excelente issue. Muy bien hecho.

@kevinmamaqi 

Hardcodeado no está, son solo algunos botones que lo tienen agregado. A mi no me gusta como queda pero no sé si sacarlo. Si prefieres que lo quite de cada botón que vaya modificando me dices.

**Comment by kevinmamaqi** [comment]
No, eso es una necesidad que se da puntualmente en algunos sitios. El CSS no puede cubrir todos los casos.
