### ISSUE TITLE
[front] Refactor TextArea with Tailwind.css

### ISSUE THREAD

**Issue by kevinmamaqi** [it-academyproject/ita-directory#221]

**Comment by felipovicc** [comment]
![image](https://user-images.githubusercontent.com/73963372/133583377-5b20045d-1a62-4ae3-ae82-f170abda332a.png)
@kevinmamaqi this is screenshot form adobe XD. Does the text area need to be wider than the inputs or must have the same size?

**Comment by kevinmamaqi** [comment]
Ah, then yes.

**Comment by felipovicc** [comment]
![image](https://user-images.githubusercontent.com/73963372/133584612-82dc5ff8-6c3f-4767-b450-c6f26a9123c7.png)

- Refactored using tailwind
- Make textarea size wider and responsive
- Add label htmlFor attr and made label font bold based on design

**Comment by felipovicc** [comment]
@kevinmamaqi will open a new pr due to an error on a class name related to vscode formatter.
