### ISSUE TITLE
[front] Fix login form input and buttons

### ISSUE THREAD

**Issue by kevinmamaqi** [it-academyproject/ita-directory#230]
Fix login form input and buttons.

<img width="1047" alt="Screen Shot 2021-09-16 at 08 30 05" src="https://user-images.githubusercontent.com/972664/133561583-2f841d15-606a-4afb-804a-d9b0cf9ea504.png">

Make it responsive.

**Comment by ManuC84** [comment]
reminder: fix issue with two labels

**Comment by ManuC84** [comment]
@kevinmamaqi 

El problema con los labels duplicados es que el componente Input ya tiene un label hardcodeado que se pasa por props. Se había añadido un label extra y no se estaba pasando el prop por ende había un label vacio extra. Ya está arreglado.

![label-props-issue](https://user-images.githubusercontent.com/66978893/133588026-1241e505-23f5-4281-b2b2-b86931c4bf11.PNG)

El form ya es responsive, lo único es que se queda en el mismo tamaño en todos los tamaños de pantalla. No sé si quieres que sea un poco más ancho en desktop y se vaya achicando a medida que se muestra en displays más pequeños. Igual no toco eso por ahora porque ya lo tienen los compañeros en otra tarea.
![responsive-login](https://user-images.githubusercontent.com/66978893/133588030-19c9a373-7d56-43ee-86ff-b0836ec7aa73.PNG)

Si lo ves bien meto PR, me avisas cualquier cosa.
