### ISSUE TITLE
[front] User project colors into tailwind.config.js

### ISSUE THREAD

**Issue by kevinmamaqi** [it-academyproject/ita-directory#233]
Normalize and use the project colors into tailwind.config.js, that way colors would be available across the whole project. Don't remove Colors constante, use it as a reference.

**Comment by ManuC84** [comment]
Added project colors to frontend/tailwind.config for usage throughout the entire app. 

Colors can be added in frontend/tailwind.config.js file 
![project-colors](https://user-images.githubusercontent.com/66978893/133578881-ef4c869d-cdc6-4324-a0fe-a474ea9bcc4c.PNG)
They can then be used as another tailwind class anywhere
![colors-usage](https://user-images.githubusercontent.com/66978893/133578896-9673ab4d-082d-494d-819f-6589d2db74e1.PNG)
