### ISSUE TITLE
Implement recover password

### ISSUE THREAD

**Issue by rubennp** [it-academyproject/ita-directory#346]
En `components/screens/RecoverPassword.js` implementar:
- [x] Conexión API
- [ ] Enviar email de recuperación de contraseña

**Comment by kevinmamaqi** [comment]
@carmeco Revisa la API y si falta algo avisame y **sobretodo** avisa a los compañeros de Node.js

**Comment by carmeco** [comment]
@vicb-rf Falta enviar el e-mail para recuperar la contraseña.
