### ISSUE TITLE
Prisma - Error: Get config: Schema Parsing P1012

### ISSUE THREAD

**Issue by marcostaimusic** [it-academyproject/ita-directory#363]
Executing ` npx prisma migrate dev init` fails to retreive the env variables. An issue was opened here [https://github.com/prisma/studio/issues/599](https://github.com/prisma/studio/issues/599)

Nonetheless, the migrations were executed and the tables inserted in the database:

![error Prisma migration](https://user-images.githubusercontent.com/77837543/142162475-f84d7a04-f16f-4898-9d06-2cc8765e4e1b.PNG)

**Comment by marcostaimusic** [comment]
After further research, and after deleting the migration and trying to re-run it, the issue repeated and did not resolve by itself. 
Checking the console of the docker container at startup, it exited and the error is similar to the following:
[https://github.com/prisma/prisma/issues/4669](https://github.com/prisma/prisma/issues/4669)
Deleting the containers and re-creating them from scratch executing `make build` and `docker compose -f docker-compose.yml up` run the recently-added migration and prevented the cointainer from crashing on startup. 
Then, each time the `docker compose -f docker-compose.yml up` is run, all migrations are executed.

**Comment by brunocangs** [comment]
Having the same issue as @PedroRoweder. Managed to fix it by downgrading to version 3.3.0. Something definitely got broken on this recently

**Comment by sauntimo** [comment]
I've had the same issue as @PedroRoweder too, I also down graded to the last known good version I had which was `3.8.1`. Note to anyone else who comes across this / future me - remember to `npm i -g prisma@3.8.1` as well as the client in your repo.

**Comment by PedroRoweder** [comment]
Running `yarn add prisma@3.3.0 @prisma/client@3.3.0` to downgrade the package did fix the issue for me as well, thanks!

**Comment by PaulOdon** [comment]
Check your "**.env**" file name, Is "**.env**" file is really named like this
My case, my "**.env**" file have named like "**.env_.example_**" and I rename my file (delete "_**.exemple**_" extension) and the issues is gone.

**Comment by Aleksey-Danchin** [comment]
Try to change PRISMA_DATABASE_URL to DATABASE_URL

**Comment by miguelgargallo** [comment]
> Check your "**.env**" file name, Is "**.env**" file is really named like this My case, my "**.env**" file has named like "**.env_.example_**" so I have renamed my file (delete "_**.exemple**_" extension) and the issues is gone.

In my case, I needed to create myself .env and include it into .gitignore, good luck 🍀

**Comment by md-neshad-tasnim** [comment]
> npm i -g prisma@3.8.1

man I downgraded to fix this env file issue. but I have the same error even tho I downgrade prisma to 3.8.1 ... so damn this error..........

**Comment by kjunghoan** [comment]
I am getting the same error on Prisma 5 with client version 5 I tried downgrading to a previous version(3.8.1) though that doesn't seem to fix this....
Any updates would be much appreciated.
