### ISSUE TITLE
Create new layout with ads, search and map

### ISSUE THREAD

**Issue by kevinmamaqi** [it-academyproject/ita-directory#365]
![Screenshot 2021-11-17 at 11 52 39](https://user-images.githubusercontent.com/972664/142187362-d2225d5e-7a7c-4693-bb27-9dae969fb09c.png)

**Comment by Pocholo77** [comment]
![Screenshot from 2021-11-21 10-00-15](https://user-images.githubusercontent.com/59293758/142756056-b2faa0f0-9d7e-435f-b9ae-7cc90141c7e8.png)
Hola Kevin! Creo que tengo un problema con los permisos que no puedo resolver , he probado desinstalar el node , el npm (sólo por probar), y no hay manera. el problema me lo da al querer hacer el commit

**Comment by Pocholo77** [comment]
![Screenshot from 2021-11-21 16-11-08](https://user-images.githubusercontent.com/59293758/142769930-7b4604b5-0467-4d41-b2b5-8a4084f422de.png)
Sólo pude solucionarlo borrando el archivo .eslintcache. Espero que no haya sido una desición muy arriesgada
